version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1021
        - -ST1012

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
